# Generated by Django 4.1.3 on 2023-02-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_photo_user_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='photos/accounts/%Y/%m', verbose_name='Основна світлина'),
        ),
    ]
