# Generated by Django 4.1.3 on 2023-03-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Електронна адреса')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Час підписки')),
            ],
            options={
                'verbose_name': 'Підписка на розсилку',
                'verbose_name_plural': 'Підписки на розсилку',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='notify_subscribers',
            field=models.BooleanField(default=False, verbose_name='Сповістити підписників'),
        ),
    ]
